name: Nsfw Upload to docker

on:
  push:
    branches: [ "main" ]

jobs:
  check_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check commit message
        run: |
          commit_message=$(git log --format=%B -n 1)
          if [[ $commit_message == deploy* ]]; then
            echo "DEPLOY=true" >> $GITHUB_ENV
          else
            echo "DEPLOY=false" >> $GITHUB_ENV
          fi
    outputs:
      deploy: ${{ env.DEPLOY }}
  uploads:
    needs: check_commit
    if: needs.check_commit.outputs.deploy == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nsfw:latest